added StartScreen and fixed uploading functions
Pylons-tech/easel_flutter pull request #16
Opened 2021-12-07 22:11 UTC by ninja-dev124

2021-12-08 04:58 UTC, haybankz requested changes

2021-12-08 04:58 UTC, haybankz commented on lib/models/media_type.dart
> +        title: 'Image',
Move string literals to the constant file

2021-12-08 04:58 UTC, haybankz commented on lib/screens/home_screen.dart
> +    setState(() {
use valueNotifier instead of setState

2021-12-08 04:58 UTC, haybankz commented on lib/screens/home_screen.dart
> +                : Container(),
use const SizedBox() instead

2021-12-08 04:58 UTC, haybankz commented on lib/screens/routing_screen.dart
> +      PylonsWallet.instance.exists().then((walletExists) async {
this is a repetition of the code line 34-36, is there a reason why we are checking if the wallet app exists twice?

2021-12-08 04:58 UTC, haybankz commented on lib/screens/start_screen.dart
> +            "Choose your NFT format",
move string to the constant file

2021-12-08 04:58 UTC, haybankz commented on lib/screens/start_screen.dart
> +                  // width: screenSize.width(),
remove dead code

2021-12-08 04:59 UTC, haybankz reviewed
Please make requested changes.

2021-12-17 10:41 UTC, kjawadDeveloper2 approved these changes
Looks good to me.

2021-12-17 17:08 UTC, starhelios approved these changes

2021-12-17 17:08 UTC, merged