Added `Choose your NFT format` screen
Pylons-tech/easel_flutter pull request #26
Opened 2022-02-03 04:37 UTC by Tiny-Angel305

This pr will add the `Choose your NFT format` screen as the first landing page of the Easel.
- Now that, recipes can be created not only from image but also from audio/video (still needs investigation for the 3d image possibility)
- Created A/V NFTs are still not shown correctly in both Easel and Wallet. Also preview for a/v nfts has to be implemented.

2022-02-03 04:54 UTC, mustafapylons reviewed
Couple of constants and statements to fix.

2022-02-03 04:54 UTC, mustafapylons commented on lib/screens/home_screen.dart
> +                              if (_currentPage.value < 4) {
The page numbers can probably be in constants.

2022-02-03 04:54 UTC, mustafapylons commented on lib/screens/home_screen.dart
> +                          } else if (_currentPage.value == 1) {
case/switch might be cleaner than an if-else.

2022-02-03 04:54 UTC, mustafapylons commented on lib/screens/mint_screen.dart
> +                            controller.jumpToPage(4);
constant use here as well.

2022-02-03 05:01 UTC, kjawadDeveloper2 requested changes
Kindly do the mentioned changes please.

2022-02-03 05:01 UTC, kjawadDeveloper2 commented on lib/screens/choose_format_screen.dart
> +  late EaselProvider provider;
No need to create an instance of the provider you can access it anywhere using context.read<EaselProvider>()

2022-02-03 05:01 UTC, kjawadDeveloper2 commented on lib/screens/choose_format_screen.dart
> +                text: 'Image',
Move all the text in a constant file.

2022-02-03 05:01 UTC, kjawadDeveloper2 commented on lib/utils/constants.dart
> -const kShareIcon = 'assets/icons/share_ic.png';
Use svg instead of png.

2022-02-03 05:01 UTC, kjawadDeveloper2 commented on lib/easel_provider.dart
> +                  IntWeightRange(
I think we should remove this .Because in case of video and audio there is no height. Or better we should make different long param based on the type eg height , width based if image and time if audio.

2022-02-03 05:01 UTC, kjawadDeveloper2 commented on lib/screens/upload_screen.dart
> +                "assets/images/file.png",
Move it to constant.

2022-02-03 23:39 UTC, Tiny-Angel305 commented on lib/screens/choose_format_screen.dart
> +  late EaselProvider provider;
@kjawadDeveloper2 , 
`provider = Provider.of<EaselProvider>(context);`
I am wondering if you say this statement is creating an instance? I think this is actually not creating an instance but just obtaining the nearest provider up its widget tree. Can you advise please?

2022-02-04 04:43 UTC, kjawadDeveloper2 commented on lib/screens/choose_format_screen.dart
> +  late EaselProvider provider;
But on other places you are trying to access it . And if its not initialize will result in run time error.

2022-02-04 05:10 UTC, Tiny-Angel305 commented on lib/screens/choose_format_screen.dart
> +  late EaselProvider provider;
Can you point out which places are those?
Also, what is the difference of using `context.read()` vs `Provider.of(context)` ? Do I have to use the former method instead?

2022-02-04 05:20 UTC, kjawadDeveloper2 commented on lib/screens/choose_format_screen.dart
> +  late EaselProvider provider;
Provider.of(context) for a change notifier by default have listen true which causes issue when you try to access in init state or places which is out side the build method. context.read and context.watch both are safer .

2022-02-04 16:14 UTC, afti-githobo commented
i don't think i have any comments that haven't already been brought up, so just gonna second the 'use more constants'

2022-02-07 00:40 UTC, Tiny-Angel305 commented on lib/utils/constants.dart
> -const kShareIcon = 'assets/icons/share_ic.png';
This icon should be revised anyway as per the new design.

2022-02-07 00:42 UTC, Tiny-Angel305 commented
@mustafapylons , @kjawadDeveloper2 , @afti-githobo , please review the fixes.

2022-02-07 11:16 UTC, kjawadDeveloper2 approved these changes
Looks Good to me.

2022-02-07 17:40 UTC, mustafapylons reviewed
Few comments to fix, otherwise clean code.

2022-02-07 17:40 UTC, mustafapylons commented on lib/easel_provider.dart
> +    } on Exception catch (e) {
instead of "e" more meaningful variable is better

2022-02-07 17:40 UTC, mustafapylons commented on lib/easel_provider.dart
> +    if (_nftFormat.format == kImageText) {
switch/case is generally more efficient than if/elseif

2022-02-07 18:07 UTC, kiroj305 commented
@mustafapylons , fixed the mentioned issues.

2022-02-07 18:11 UTC, mustafapylons approved these changes
Looks good to me now.

2022-02-07 18:12 UTC, merged