Support audio preview
Pylons-tech/easel_flutter pull request #30
Opened 2022-02-10 17:35 UTC by Tiny-Angel305

- Added a basic audio player
- Pass in `NFT_Format` param through the recipe creation

2022-02-10 18:03 UTC, mustafapylons reviewed
one small fix, otherwise clean code.

2022-02-10 18:03 UTC, mustafapylons commented on lib/widgets/audio_widget.dart
> +    } catch (e) {
more meaningful variable than "e"

2022-02-11 06:18 UTC, kjawadDeveloper2 requested changes
Kindly solve these issues.

2022-02-11 06:18 UTC, kjawadDeveloper2 commented on lib/screens/mint_screen.dart
> +                  provider.nftFormat.format == kImageText
Use spread operator.

2022-02-11 06:18 UTC, kjawadDeveloper2 commented on lib/widgets/audio_widget.dart
> +    _durationState = Rx.combineLatest2<Duration, PlaybackEvent, DurationState>(
Whats your intention of using Rx here?

2022-02-11 06:18 UTC, kjawadDeveloper2 commented on pubspec.yaml
> +  just_audio: ^0.9.19
This audio package is very buggy on the ios side. Is there any other package.

2022-02-11 19:28 UTC, Tiny-Angel305 commented on pubspec.yaml
> +  just_audio: ^0.9.19
@kjawadDeveloper2 , can you recommend one for me?

2022-02-11 19:42 UTC, Tiny-Angel305 commented on pubspec.yaml
> +  just_audio: ^0.9.19
I found https://pub.dev/packages/audio_manager as the best audio plugin in flutter. Let me know your thought.

2022-02-14 18:22 UTC, Tiny-Angel305 commented
@mustafapylons , @kjawadDeveloper2 
Please review the fixes done.

2022-02-14 18:24 UTC, mustafapylons approved these changes
Looks good to me after the fix.

2022-02-14 18:35 UTC, kjawadDeveloper2 approved these changes
Looking good from my end.

2022-02-14 18:35 UTC, merged