Solve PS 78
Pylons-tech/easel_flutter pull request #33
Opened 2022-02-20 08:57 UTC by kjawadDeveloper2

Solve the issue in which the dialog still appears when the user come back.

2022-02-20 17:28 UTC, Tiny-Angel305 requested changes
@kjawadDeveloper2 , I tried the `fix/ps_78` branch. It's occurring an error (Username not found) while fetching the wallet profile, though I already logged in the Wallet. What's the issue?

2022-02-20 22:23 UTC, mustafapylons reviewed
One small typo, otherwise good code.

2022-02-20 22:23 UTC, mustafapylons commented on lib/screens/routing_screen.dart
> +        print("OnFocusFained again");
typo to fix, "OnFocusGained again"

2022-02-21 12:40 UTC, kjawadDeveloper2 commented
@Tiny-Angel305  this fetching is because of the grpc url change. I have added another PR which is already approved and merge. Can you check with the new wallet code?

2022-02-21 16:41 UTC, Tiny-Angel305 commented
@kjawadDeveloper2 , just checked this PR again along with the latest wallet main branch. No luck yet tho. Easel keeps trying to fetch the profile again and again.

2022-02-21 18:24 UTC, Tiny-Angel305 approved these changes

2022-02-21 18:27 UTC, merged