Feat/nft data input
Pylons-tech/easel_flutter pull request #4
Opened 2021-11-03 17:07 UTC by haybankz

### Description
Adds NFT file and text data input features, previews inputted data on preview screen

2021-11-03 17:15 UTC, kjawadDeveloper2 requested changes
Kindly solve these issues.

2021-11-03 17:15 UTC, kjawadDeveloper2 commented on lib/easel_provider.dart
> +  GlobalKey<FormState> formKey = GlobalKey<FormState>();
Move formkey from the provider. It creates issue when you do hotrestart.

2021-11-03 17:15 UTC, kjawadDeveloper2 commented on lib/main.dart
> +          primarySwatch: Colors.blue,
Specify whole app theme here.

2021-11-03 17:15 UTC, kjawadDeveloper2 commented on pubspec.yaml
> +  file_picker: ^4.2.0
Kindly also put details on why this dependency is used.

2021-11-03 17:15 UTC, kjawadDeveloper2 commented on lib/screens/upload_screen.dart
> +                setState(() {
No set state.

2021-11-03 17:15 UTC, kjawadDeveloper2 commented on lib/screens/upload_screen.dart
> +              child: Image.asset("assets/icons/file.png",),
Centralize assets in one file.

2021-11-04 05:15 UTC, haybankz commented
@kjawadDeveloper2 issues have been solved

2021-11-04 05:17 UTC, kjawadDeveloper2 approved these changes
Looks good from myside.

2021-11-04 18:10 UTC, starhelios approved these changes

2021-11-04 18:10 UTC, merged