Tutorial screens implementation
Pylons-tech/easel_flutter pull request #46
Opened 2022-03-23 21:05 UTC by Tiny-Angel305

Added a page view containing tutorial 1, 2, 3

2022-03-23 21:24 UTC, mustafapylons reviewed
few small issues, otherwise good clean code.

2022-03-23 21:24 UTC, mustafapylons commented on lib/screens/tutorial_screen.dart
> +              if (kTutorialItems.indexOf(item) == 2) ...[
number "2" can be in a constant variable.

2022-03-23 21:24 UTC, mustafapylons commented on lib/screens/tutorial_screen.dart
> +          if (currentPage.round() == 2) ...[
number "2" can be in a constant variable.

2022-03-24 12:03 UTC, kjawadDeveloper2 requested changes
Kindly solve these minor issues.

2022-03-24 12:03 UTC, kjawadDeveloper2 commented on lib/screens/tutorial_screen.dart
> +                              fontSize: 12.0,
Use sp for text.

2022-03-24 12:03 UTC, kjawadDeveloper2 commented on lib/screens/tutorial_screen.dart
> +                        margin: const EdgeInsets.only(right: 10, bottom: 2),
use 10.w and 2.h to make it responsive.

2022-03-24 12:03 UTC, kjawadDeveloper2 commented on lib/screens/tutorial_screen.dart
> +                        print("clicked bubble!");
Remove print.

2022-03-24 12:03 UTC, kjawadDeveloper2 commented on lib/screens/tutorial_screen.dart
> +                        color: Color(0xFF333333)),
Add color in constant file.

2022-03-24 12:03 UTC, kjawadDeveloper2 commented on lib/screens/tutorial_screen.dart
> +                        color: Color(0xFF333333)),
Add color in a constant file.

2022-03-24 21:44 UTC, Tiny-Angel305 commented
@mustafapylons , @kjawadDeveloper2 .
All issues pointed out above are now fixed.

2022-03-24 21:46 UTC, mustafapylons approved these changes
Looks good to me after the changes.

2022-03-25 09:40 UTC, kjawadDeveloper2 approved these changes
Looks good to me.

2022-03-25 09:40 UTC, merged