Complete onboarding
Pylons-tech/easel_flutter pull request #48
Opened 2022-03-28 06:33 UTC by Tiny-Angel305

This pr will basically finalize the onboarding screens implementation of Easel.

2022-03-28 14:24 UTC, mustafapylons approved these changes
Looks good to me.

2022-03-30 18:13 UTC, kjawadDeveloper2 requested changes
Kindly solve this issue.

2022-03-30 18:13 UTC, kjawadDeveloper2 commented on lib/screens/welcome_screen.dart
> +                Navigator.push(
Kindly make name routes.

2022-03-30 18:13 UTC, kjawadDeveloper2 commented on lib/screens/tutorial_screen.dart
>                        Navigator.push(
Kindly make name routes.

2022-03-30 21:57 UTC, Tiny-Angel305 commented
@kjawadDeveloper2 , migrated to the named routes navigation as per your request. Will be gradually making all other navigations use named routes.

2022-03-31 04:35 UTC, kjawadDeveloper2 commented
@Tiny-Angel305  did you pushed the code?

2022-03-31 04:38 UTC, Tiny-Angel305 commented
@kjawadDeveloper2 , sorry I just pushed the fixes.

2022-03-31 04:40 UTC, kjawadDeveloper2 approved these changes
Looking good from my side.

2022-03-31 04:40 UTC, merged