Revise "Upload your NFT file" screen
Pylons-tech/easel_flutter pull request #49
Opened 2022-04-04 20:05 UTC by Tiny-Angel305

- Remove "Choose your NFT format" screen
- Revise "Upload your NFT file" screen
- Fix the file picker logic as per the UI flow change
- Some more refactoring

2022-04-04 21:06 UTC, mustafapylons reviewed
one small comment, otherwise code is good.

2022-04-04 21:06 UTC, mustafapylons commented on lib/models/nft_format.dart
> +      if (i == 4) {
number "4" should be in a constant.

2022-04-05 05:09 UTC, kjawadDeveloper2 requested changes
Kindly solve these issues.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/easel_provider.dart
> +          .showSnackBar(SnackBar(content: Text(uploadResponse.errorMessage ?? "Upload error occurred")));
Kindly move Upload error occurred in a constant file.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/easel_provider.dart
> +          .showSnackBar(const SnackBar(content: Text("Recipe created")));
Kindly also move Recipe created in a constant file.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/easel_provider.dart
> +          .showSnackBar(SnackBar(content: Text("Recipe error : ${response.error}")));
Same constant file.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/easel_provider.dart
> +    ScaffoldMessenger.of(navigatorKey.currentState!.overlay!.context)
Can you make extension over this as it is used alot.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/screens/home_screen.dart
> +                                        fontSize: 20, color: EaselAppTheme.kBlue, fontWeight: FontWeight.w400),
User 20.sp.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/screens/upload_screen.dart
> +                              errorText.value = 'Pick a file';
Kindly move it to a constant file.

2022-04-05 05:09 UTC, kjawadDeveloper2 commented on lib/screens/upload_screen.dart
> +                      content: Text("Unsupported format."),
Kindly move it to a constant file.

2022-04-05 13:27 UTC, mike-gallego approved these changes
some constant changes, as others stated, but looks good

2022-04-05 17:45 UTC, kiroj305 commented on lib/easel_provider.dart
> +    ScaffoldMessenger.of(navigatorKey.currentState!.overlay!.context)
@kjawadDeveloper2 , what did you mean here?

2022-04-05 18:32 UTC, Tiny-Angel305 commented
@mustafapylons , @kjawadDeveloper2 
Please review again, the issues mentioned above were fixed. Note please this is not full completion of the upload screen so I'll try to knock out all other minor issues still remained during the next PR.

2022-04-05 18:37 UTC, kjawadDeveloper2 commented
I see you have added the extension but i don't see you are using it . @Tiny-Angel305  can you confirm ?

2022-04-05 18:39 UTC, Tiny-Angel305 commented
Only used it in upload_screen which is in progress atm. As said, I am gonna fix minor issues during the next PR including the one you just pointed out. Would it be okay?

2022-04-05 18:40 UTC, kjawadDeveloper2 commented
You can do snackbar fix in this and remaining in the next PR.

2022-04-05 18:41 UTC, Tiny-Angel305 commented
ok will do then.

2022-04-05 18:49 UTC, mustafapylons approved these changes
Looks good to me now.

2022-04-05 18:51 UTC, Tiny-Angel305 commented
@kjawadDeveloper2 , snackbar fix done.

2022-04-05 18:56 UTC, kjawadDeveloper2 approved these changes
Looks good from my side.

2022-04-05 18:59 UTC, merged