completed publish page layout
Pylons-tech/easel_flutter pull request #5
Opened 2021-11-04 17:57 UTC by NazymBerdaliyeva

2021-11-04 20:15 UTC, mustafapylons approved these changes
At Line 24, please change Max:10000 to reflect the update from Product Management for Max number of editions.
Otherwise it's good clean code.

2021-11-05 05:04 UTC, kjawadDeveloper2 requested changes
Kindly make these changes.

2021-11-05 05:04 UTC, kjawadDeveloper2 commented on lib/screens/home_screen.dart
> +                                  setState(() {
Dont use setState

2021-11-05 05:04 UTC, kjawadDeveloper2 commented on lib/screens/home_screen.dart
> +                                    color: Color(0xFF1212C4),
Color should be provided through theme.

2021-11-05 05:04 UTC, kjawadDeveloper2 commented on lib/widgets/rounded_purple_button_widget.dart
> +            Color.fromRGBO(255, 255, 255, 0.2),
Centralize all the colors.

2021-11-06 10:13 UTC, NazymBerdaliyeva commented on lib/screens/home_screen.dart
> +                                  setState(() {
okay

2021-11-06 10:21 UTC, NazymBerdaliyeva commented on lib/screens/home_screen.dart
> +                                    color: Color(0xFF1212C4),
okay

2021-11-06 10:23 UTC, NazymBerdaliyeva commented on lib/widgets/rounded_purple_button_widget.dart
> +            Color.fromRGBO(255, 255, 255, 0.2),
okay

2021-11-06 10:57 UTC, kjawadDeveloper2 approved these changes
Looks Good from my side.

2021-11-06 20:14 UTC, starhelios approved these changes

2021-11-06 20:14 UTC, merged