Create nft
Pylons-tech/easel_flutter pull request #9
Opened 2021-11-08 17:01 UTC by haybankz

### Description
adds creation of NFT from data inputted by user

I have
- [ ] implemented upload of NFT image on nft.storage
- [ ] implemented share functionality (Easel generated URL)

2021-11-08 17:31 UTC, kjawadDeveloper1 requested changes

2021-11-08 17:31 UTC, kjawadDeveloper1 commented on lib/screens/home_screen.dart
> +                                          color: const Color(0xFF1212C4),
Centralize the colors please.

2021-11-08 17:31 UTC, kjawadDeveloper1 commented on lib/screens/home_screen.dart
> +                                  color: Color(0xFF1212C4),
Centralize the colors.

2021-11-08 17:48 UTC, mustafapylons commented on lib/screens/description_screen.dart
> +                          if(int.parse(value) > 10000) return "Maximum is 10,000";
Let's not use Magic numbers in the code (like 10000, use constants etc.)

2021-11-08 17:54 UTC, mustafapylons reviewed
Left comments, please correct them before approval.

2021-11-08 17:54 UTC, mustafapylons commented on lib/screens/description_screen.dart
> +                          if(value.length <= 20) return "Enter more than 20 characters";
Same here, maximum values, boundaries etc. should be in constant variables.

2021-11-08 17:54 UTC, mustafapylons commented on lib/utils/file_utils.dart
> +    // finally to Bitmap
Dead Code in multiple places, please remove dead code.

2021-11-08 17:54 UTC, mustafapylons commented on lib/datasources/remote_datasource.dart
> +    }).catchError((e) => ApiResponse<StorageResponseModel>.error(errorMessage: e.toString()));
Use meaningful variables, not "e".

2021-11-08 21:02 UTC, haybankz commented
@kjawadDeveloper1 @mustafapylons review issues have been resolved

2021-11-08 21:07 UTC, mustafapylons approved these changes

2021-11-08 22:12 UTC, starhelios approved these changes

2021-11-09 04:14 UTC, kjawadDeveloper2 approved these changes
Looking Good from my side.

2021-11-09 08:02 UTC, merged